import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
      <header
  style={{ backgroundColor: "#1B3659" }}
  className="text-white px-4 py-3 flex items-center gap-6 shadow-md"
>
  <Link href="/" className="font-bold text-lg">
    Joe’s Reviews
  </Link>
  <Link href="/" className="hover:underline">Home</Link>
  <Link href="/profile" className="hover:underline">Profile</Link>
</header>

  {children}
</body>

    </html>
  );
}
