import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
  <header
    style={{ backgroundColor: "#1B3659" }}
    className="text-white px-4 py-3 flex items-center gap-6 shadow-md"
  >
    <a href="/" className="font-bold text-lg">
      Joe’s Reviews
    </a>
    <a href="/" className="hover:underline">Home</a>
    <a href="/profile" className="hover:underline">Profile</a>
  </header>
  {children}
</body>

    </html>
  );
}
